language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - rbx-2.1.1
  - jruby-19mode

gemfile:
  - Gemfile
  - tests/rails-2.3/Gemfile
  - tests/rails-3.2/Gemfile

before_script: "bundle exec rake tests:bundle"
