source 'https://rubygems.org'

gem 'rails', '~>2.3'

gem 'mysql2', '~>0.2.1'
gem 'activerecord-mysql2-adapter'
gem 'ruby-debug', :platforms => :ruby_18
gem 'database_cleaner'

gem "capybara", "1.1.1"
gem "cucumber", "1.1.0"
gem "cucumber-rails", '=0.3.2'
gem 'rspec-rails', '~>1.3'


gem 'spreewald', :path => '../..'
