#!/usr/bin/env rake
require 'cucumber/rake/task'

desc 'Default: Run all specs for a specific rails version.'
task :default => :features

desc 'Run all specs for rails 2.3'
Cucumber::Rake::Task.new(:features) do |t|
  feature = if ENV['SINGLE_FEATURE']
    "../shared/features/shared/#{ ENV['SINGLE_FEATURE'] }"
  else
    'features/shared'
  end

  # tell cucumber where it finds it files (subdirectories and symlinks are confusing it)
  t.cucumber_opts = "--require features --require features/shared #{feature}"
end
