source 'https://rubygems.org'

gem 'rails', '~>3.2'
gem "sqlite3", :platform=>:ruby
gem 'database_cleaner'
gem 'capybara', "~>1" # for ruby 1.8.7 compatibility
gem 'cucumber-rails'
gem 'cucumber', '1.3.8'
gem 'selenium-webdriver'

gem 'rspec-rails'
gem 'haml-rails'

gem 'gemika'

gem 'spreewald', :path => '../..'


