source 'https://rubygems.org'

gem 'rails', '~>3.2'
gem "sqlite3", :platform=>:ruby
gem 'haml-rails'
gem 'gemika'

gem 'pry'

group :test do
  gem 'database_cleaner'
  gem 'launchy'
  gem 'capybara', "~>1" # for ruby 1.8.7 compatibility
  gem 'cucumber-rails'
  gem 'cucumber', '1.3.8', require: false
  gem 'selenium-webdriver'
  gem 'rspec-rails'
  gem 'spreewald', :path => '../..'
end