source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'

gem 'rails', '~>6.0'
gem 'sqlite3'
gem 'haml-rails'
gem 'gemika', '~>0.5'

group :development, :test do
  gem 'byebug'
  gem 'pry'
end

group :test do
  gem 'database_cleaner'
  gem 'capybara', "~>3"
  gem 'capybara-screenshot'
  gem 'cucumber-rails', require: false
  gem 'cucumber'
  gem 'selenium-webdriver'
  gem 'rspec-rails'
  gem 'spreewald', :path => '../..'
end
