source 'https://rubygems.org'

gem 'rails', '~>3.2'
gem "sqlite3", :platform=>:ruby
gem 'ruby-debug', :platforms => :ruby_18
gem "jruby-openssl", :platform=>:jruby
gem "activerecord-jdbcsqlite3-adapter", :platform=>:jruby
gem 'database_cleaner'
gem 'capybara', "~>1" # for ruby 1.8.7 (capybara 2.x requires ruby 1.9)

gem 'rspec-rails'
gem 'spreewald', :path => '../..'

gem 'haml-rails'
