#!/usr/bin/env rake
require 'cucumber/rake/task'

desc 'Default: Run all specs for a specific rails version.'
task :default => :features

desc 'Run all specs for rails 3.2'
Cucumber::Rake::Task.new(:features) do |t|
  # tell cucumber where it finds it files (subdirectories and symlinks are confusing it)
  feature = ENV['FEATURE'] || "features/shared"
  t.cucumber_opts = "--require features --require features/shared #{feature}"
end

