source 'https://rubygems.org'


gem 'rails', '<5'
gem 'sqlite3'
gem 'haml-rails'
gem 'gemika', '~>0.5'


group :development, :test do
  gem 'byebug'
  gem 'pry'
end

group :test do
  gem 'database_cleaner'
  gem 'capybara', "~>3"
  gem 'capybara-screenshot'
  gem 'cucumber-rails', require: false
  gem 'cucumber'
  gem 'selenium-webdriver'
  gem 'rspec-rails'
  gem 'spreewald', :path => '../..'
end
