---
name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.4.5
          gemfile: tests/rails-4_capybara-3/Gemfile
          folder: tests/rails-4_capybara-3
        - ruby: 2.6.6
          gemfile: tests/rails-6_capybara-3/Gemfile
          folder: tests/rails-6_capybara-3
        - ruby: 2.4.5
          gemfile: Gemfile.ruby245
          folder: ~
        - ruby: 2.6.6
          gemfile: Gemfile.ruby266
          folder: ~
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v2
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Bundle
      run: |
        gem install rake
        bundle install --no-deployment
    - if: startsWith(matrix.gemfile, 'tests')
      name: Run cucumber tests
      run: cd "${{ matrix.folder }}" && bundle exec rake matrix:cucumber_tests
    - if: startsWith(matrix.gemfile, 'Gemfile')
      name: Run all tests
      run: bundle exec rake matrix:all_tests
